#!/usr/bin/env bash
set -euo pipefail

command=shell
args=(--check)
scenario=nixbitcoinorg
if [[ $# > 0 && $1 != -* ]]; then
  scenario=$1
  shift
fi
case ${1-} in
  --test|-t)
    shift
    command=test
    args=()
    ;;
esac
case ${1-} in
  --analyze|-a)
    analyze=1
    shift
    args=(--check --run systemd-analyze critical-chain)
    ;;
esac

if ! nixosContainer=$(type -p nixos-container) \
        || grep -q '"/etc/nixos-containers"' "$nixosContainer"; then
    attr=container
else
    # NixOS <22.05
    attr=containerLegacy
fi

cd "${BASH_SOURCE[0]%/*}"
nix run -L "..#tests.$scenario.$attr" -- "$command" "${args[@]}" "$@"
