#!/usr/bin/env bash
set -euo pipefail

args=(--check)
scenario=nixbitcoinorg-container
if [[ $# > 0 && $1 != -* ]]; then
  scenario=$1
  shift
fi
case ${1-} in
  --test|-t)
    test=1
    shift
    args=(--command test)
    ;;
esac
case ${1-} in
  --analyze|-a)
    analyze=1
    shift
    args=(--check --run systemd-analyze critical-chain)
    ;;
esac

exec run-node -s "$scenario" container "${args[@]}" "$@"
