#!/usr/bin/env bash
set -euo pipefail

cd "${BASH_SOURCE[0]%/*}"

# Sets vars `push`, `action`
source lib/parse-deploy-args.sh

echo
echo "Instantiating system"
drv=$(nix eval --raw ..#systemDrv.drvPath)

echo
echo "Copying derivation"
nix copy --substitute-on-destination --derivation "$drv" --to ssh-ng://$remoteHost

echo
./deploy-secrets

echo
echo "Building system on remote host"
ssh -n $remoteHost "nix build -L --out-link /tmp/system $drv"

echo
echo "Switching to configuration"
ssh -n $remoteHost "/tmp/system/bin/switch-to-configuration $action"

if [[ $push && -d ../.git ]]; then
    echo
    echo 'Pushing branch `deployed`'
    git push -f git@github.com:fort-nix/nixbitcoin.org.git HEAD:deployed
fi
