#!/usr/bin/env bash
set -euo pipefail

umask u=rwx,go=

# Enable reproducible globbing
export LC_COLLATE=C

secretsDir=$root/secrets/nix-bitcoin
remoteSecretsDir=/var/src/secrets

secretsHash=$(sha256sum "$secretsDir"/*.gpg | sha256sum)
remoteSecretsHash=$(ssh -n $remoteHost "cat $remoteSecretsDir/.secrets_hash 2>/dev/null || :")

if [[ $secretsHash == $remoteSecretsHash ]]; then
    echo "Secrets are already up to date"
    exit 0
fi

echo "Transferring secrets"

tmpDir=$(mktemp -d /tmp/nixbitcoinorg-pass.XXX)
trap "rm -rf $tmpDir" EXIT

for pass in $(cd "$secretsDir"; echo *.gpg); do
    secret=${pass%.gpg}
    pass show "nix-bitcoin/$secret" > "$tmpDir/$secret"
done

rsync \
  -av --no-owner --no-group --no-times \
  --delete-excluded \
  --mkpath \
  $tmpDir/ \
  $remoteHost:$remoteSecretsDir \
  >&2

echo "$secretsHash" | ssh $remoteHost "umask u=rw,go=; cat > $remoteSecretsDir/.secrets_hash"
