#!/usr/bin/env bash
set -euo pipefail

cd "${BASH_SOURCE[0]%/*}"

# Sets vars `push`, `action`
source lib/parse-deploy-args.sh

echo
echo "Building"
system=$(./build)

echo
echo "Copying system"
nix copy --to ssh://$remoteHost $system

echo
./deploy-secrets

echo
echo "Switching to configuration"
ssh -n $remoteHost "$system/bin/switch-to-configuration $action"

if [[ $push && -d ../.git ]]; then
    echo
    echo 'Pushing branch `deployed`'
    git push -f git@github.com:fort-nix/nixbitcoin.org.git HEAD:deployed
fi
