#!/usr/bin/env bash
set -euo pipefail
cd "${BASH_SOURCE[0]%/*}"

# Show the all nginx configuration files of the website config

config=$(nix build --no-link --print-out-paths '..#system.config.environment.etc."nginx/nginx.conf".source')
commonConfig=$(cat "$config" | grep -ohP '(?<=include )/nix/store.*common.conf' | head -1)
cat "$config"
echo
echo "Common config"
cat "$commonConfig"
