#!/usr/bin/env bash
set -euo pipefail

# Usage:
# echo mycontent | ./add-secret mydir/mysecret

# Disable auto-committing
if [[ ! -e /tmp/nixbitcoin.org/bin/git ]]; then
    mkdir -p /tmp/nixbitcoin.org/bin
    ln -s $(which true) /tmp/nixbitcoin.org/bin/git
fi
export PATH=/tmp/nixbitcoin.org/bin:$PATH

export PASSWORD_STORE_DIR=$(cd "${BASH_SOURCE[0]%/*}" && pwd)
pass insert --multiline "$@"
